In [1]:
import pandas as pd
dataset = pd.read_csv('./dataset.csv')

In [2]:
sex = dataset['Sex']

In [3]:
sex

0        Male
1      female
2      female
3      female
4        Male
        ...  
884      Male
885    female
886    female
887      Male
888      Male
Name: Sex, Length: 889, dtype: object

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [5]:
oe = OrdinalEncoder(categories=[['Male','female']])

In [7]:
result = oe.fit_transform(sex.values.reshape(-1,1))

In [8]:
result

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

***One Hot Encoding***
Two Ways
- Pandas Get Dummy
- Sklean OneHotEncoder

In [10]:
#Using Pandas
pd.get_dummies(dataset,columns=['Sex'])

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Embarked  \
0              1         0       3  22.0      1      0   7.2500         3   
1              2         1       1  38.0      1      0  71.2833         1   
2              3         1       3  26.0      0      0   7.9250         3   
3              4         1       1  35.0      1      0  53.1000         3   
4              5         0       3  35.0      0      0   8.0500         3   
..           ...       ...     ...   ...    ...    ...      ...       ...   
884          887         0       2  27.0      0      0  13.0000         3   
885          888         1       1  19.0      0      0  30.0000         3   
886          889         0       3  60.0      1      2  23.4500         3   
887          890         1       1  26.0      0      0  30.0000         1   
888          891         0       3  32.0      0      0   7.7500         2   

     Sex_Male  Sex_female  
0        True       False  
1       False        True  
2       False        True  
3       False        True  
4        True       False  
..        ...         ...  
884      True       False  
885     False        True  
886     False        True  
887      True       False  
888      True       False  

[889 rows x 10 columns]

In [9]:
dataset

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    Male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    Male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
884          887         0       2    Male  27.0      0      0  13.0000   
885          888         1       1  female  19.0      0      0  30.0000   
886          889         0       3  female  60.0      1      2  23.4500   
887          890         1       1    Male  26.0      0      0  30.0000   
888          891         0       3    Male  32.0      0      0   7.7500   

     Embarked  
0           3  
1           1  
2           3  
3           3  
4           3  
..        ...  
884         3  
885         3  
886         3  
887         1  
888         2  

[889 rows x 9 columns]

In [11]:
#Using Sklearn Library
from sklearn.preprocessing import OneHotEncoder

In [12]:
ohe = OneHotEncoder()

In [13]:
#working with onehotencoder you get a sparse array
#you make toarray method to convert it into Array
#then again concat it into Dataframe
result = ohe.fit_transform(dataset[['Sex']]).toarray()

In [14]:
result  

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [15]:
import numpy as np

In [18]:
np.hstack((dataset[['SibSp','Survived','Embarked','Fare','Pclass','Age','Parch']].values,result))

array([[1., 0., 3., ..., 0., 1., 0.],
       [1., 1., 1., ..., 0., 0., 1.],
       [0., 1., 3., ..., 0., 0., 1.],
       ...,
       [1., 0., 3., ..., 2., 0., 1.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 0., 2., ..., 0., 1., 0.]])

In [16]:
dataset

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0              1         0       3    Male  22.0      1      0   7.2500   
1              2         1       1  female  38.0      1      0  71.2833   
2              3         1       3  female  26.0      0      0   7.9250   
3              4         1       1  female  35.0      1      0  53.1000   
4              5         0       3    Male  35.0      0      0   8.0500   
..           ...       ...     ...     ...   ...    ...    ...      ...   
884          887         0       2    Male  27.0      0      0  13.0000   
885          888         1       1  female  19.0      0      0  30.0000   
886          889         0       3  female  60.0      1      2  23.4500   
887          890         1       1    Male  26.0      0      0  30.0000   
888          891         0       3    Male  32.0      0      0   7.7500   

     Embarked  
0           3  
1           1  
2           3  
3           3  
4           3  
..        ...  
884         3  
885         3  
886         3  
887         1  
888         2  

[889 rows x 9 columns]